In [1]:
import numpy as np
import tensorflow as tf

## Creating Tensor

In [2]:
# list
list_1 = [1,2,3]
list_1

[1, 2, 3]

## Array 

In [3]:
arr = np.array([list_1])
arr

array([[1, 2, 3]])

## Tensor

In [4]:
tensor = tf.constant(list_1)
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

In [5]:
# Also can pass tuple
tuple_2x2 = [[1,2,3],[4,5,6]]
tensor = tf.constant(tuple_2x2)
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [6]:
tensor.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

## Validating the Tensor

In [7]:
for i in dir(tf):
    print(i, end = "  -->  ")

AggregationMethod  -->  Assert  -->  CriticalSection  -->  DType  -->  DeviceSpec  -->  GradientTape  -->  Graph  -->  IndexedSlices  -->  IndexedSlicesSpec  -->  Module  -->  Operation  -->  OptionalSpec  -->  RaggedTensor  -->  RaggedTensorSpec  -->  RegisterGradient  -->  SparseTensor  -->  SparseTensorSpec  -->  Tensor  -->  TensorArray  -->  TensorArraySpec  -->  TensorShape  -->  TensorSpec  -->  TypeSpec  -->  UnconnectedGradients  -->  Variable  -->  VariableAggregation  -->  VariableSynchronization  -->  _API_MODULE  -->  _LazyLoader  -->  __all__  -->  __builtins__  -->  __cached__  -->  __compiler_version__  -->  __cxx11_abi_flag__  -->  __doc__  -->  __file__  -->  __git_version__  -->  __internal__  -->  __loader__  -->  __monolithic_build__  -->  __name__  -->  __operators__  -->  __package__  -->  __path__  -->  __spec__  -->  __version__  -->  _absolute_import  -->  _api  -->  _compat  -->  _current_file_location  -->  _current_module  -->  _distutils  -->  _division  -

In [8]:
tensor.shape

TensorShape([2, 3])

In [9]:
#dir(tf.keras)

In [10]:
#tensr = tf.constant?
#tensor = tf.constant


In [11]:
tensr = tf.constant